source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RSFast_Example', :exclusive => true do
  pod "RSFast", :path => "../"
end

target 'RSFast_Tests', :exclusive => true do
  pod "RSFast", :path => "../"

  pod 'FBSnapshotTestCase'
end
